# Generated by Django 4.2.7 on 2024-04-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='Product',
            new_name='product',
        ),
    ]
